trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016
  demands:
  - java
  - azureps

variables:
  - group: SonarHostedVariables

steps:
  - task: EnterpriseServicesDevOpsTeam.BuildTool-Tasks.task-ESDevopsCIConfig.ServicesDevOpsBuildConfig@5
    displayName: ServicesDevOpsBuildConfig
    inputs:
      ServicesDevOpsServiceEndpoint: ServicesDevOpsEndpoint

  - powershell: |
     # Write your PowerShell commands here.
   
     Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
   
    displayName: 'PowerShell Script'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'CredentialScanner'
    inputs:
      toolMajorVersion: V2
      outputFormat: csv
      debugMode: false

  - task: EnterpriseServicesDevOpsTeam.BuildTool-Tasks.task-ServicesDevopsAddToSonarNSG.ServicesDevOpsSonarPreReq@5
    displayName: 'T-ServicesDevOpsSonarPreReq:'

  - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@4
    displayName: 'Prepare analysis on SonarQube'
    inputs:
      SonarQube: 'ServicesSonar-Corp'
      scannerMode: CLI
      configMode: manual
      cliProjectKey: 'Infra_as_code_source_Components_master'
      cliProjectName: 'Infra_as_code_source_Components_master_#SI'
      cliProjectVersion: '$(Build.buildNumber)'

  - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@4
    displayName: 'Run Code Analysis'

  - task: EnterpriseServicesDevOpsTeam.BuildTool-Tasks.task-ServicesDevopsRemoveFromNSG.ServicesDevOpsSonarPreReqComplete@5
    displayName: 'T-ServicesDevOpsSonarPreReqComplete:'

  - task: azsdktm.AzSDK-task.azsk-cicd-armchecker.AzSKARMTemplateChecker@4
    displayName: 'AzSK_ARMTemplateChecker '
    inputs:
      ARMTemplateFilePath: Modules/ARM
    continueOnError: true

  - task: EnterpriseServicesDevOpsTeam.BuildTool-Tasks.task-ESDevopsValidateCIConfig.ServicesDevOpsValidateBuildConfig@5
    displayName: ServicesDevOpsValidateBuildConfig

  - task: EnterpriseServicesDevOpsTeam.BuildTool-Tasks.task-ESDevopsCopyReports.ServicesDevOpsCopyReports@5
    displayName: ServicesDevOpsCopyReports

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: BuildLogFolder'
    inputs:
      PathtoPublish: '$(Agent.BuildDirectory)\BuildLogFolder'
      ArtifactName: BuildLogFolder

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'