FROM mcr.microsoft.com/azure-powershell:4.7.0-ubuntu-18.04

WORKDIR /azp

COPY .token .
COPY Scripts/start.sh .
COPY Scripts/Install-AzPowerShell.ps1 .

RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update \
    && apt-get install apt-utils -qq

RUN apt-get install -qq --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    file \
    ftp \
    jq \
    git \
    gnupg \
    iproute2 \
    iputils-ping \
    locales \
    lsb-release \
    netcat \
    sudo \
    time \
    unzip \
    wget \
    zip \ 
    software-properties-common \
&& rm -rf /var/lib/apt/lists/* && apt-get clean

# Install Docker
ENV DOCKER_VERSION 19.03.9
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz \
    && tar --strip-components=1 -xvzf docker-$DOCKER_VERSION.tgz -C /usr/local/bin && rm docker-$DOCKER_VERSION.tgz

# Install Kubectl
ENV KUBE_VERSION 1.19.0
RUN curl -fsSLO https://storage.googleapis.com/kubernetes-release/release/v$KUBE_VERSION/bin/linux/amd64/kubectl \
    && mv kubectl /usr/local/bin && chmod 755 /usr/local/bin/kubectl

# Install terraform
ENV TERRAFORM_VERSION 0.13.4
RUN curl -fsSLO https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin \
    && chmod 755 /usr/local/bin/terraform && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Install Az cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install Az.* PowerShell modules
RUN pwsh -Command "Install-Module Az -Force -RequiredVersion 4.7.0"
RUN pwsh -Command "Install-Module Az.NetAppFiles -Force"
#    && pwsh -Command "Find-Module Az.* | Install-Module -Force"

# Install Pipeline Agents
RUN chmod +x start.sh

CMD ["./start.sh"]