name: Create Azure Pipelines

variables:
- template: /Modules/ARM/.global/global.variables.yml
- name: PAT
  value: '$(System.AccessToken)'
- name: OrganizationUri
  value: '$(System.TeamFoundationCollectionUri)'
- name: ProjectName
  value: '$(System.TeamProject)'
- name: RepositoryName
  value: '$(Build.Repository.Name)'

trigger:
  batch: true
  branches:
    include:
    - notrigger
  paths:
    include:
    - Utilities/Tools/*

stages:
- stage: CreateAzurePipelines
  displayName: Create Azure Pipelines
  jobs:
  - job:
    displayName: Create Azure Pipelines
    pool:
      ${{ if eq(variables['vmImage'], '') }}:
        name: $(poolName)
      ${{ if eq(variables['poolName'], '') }}:
        vmImage: $(vmImage)
    steps:
    - task: AzurePowerShell@5
      enabled: true
      displayName: Create Azure Pipelines
      inputs:
        azureSubscription: $(serviceConnection)
        azurePowerShellVersion: LatestVersion
        preferredAzurePowerShellVersion: $(preferredAzurePowerShellVersion)
        pwsh: true
        ScriptType: InlineScript
        inline: |
          . "$(System.DefaultWorkingDirectory)/Utilities/Tools/New-AdoPipeline.ps1"
          $OrganizationName = '$(OrganizationUri)'

          $functionInput = @{
            PAT               = '$(PAT)'
            OrganizationName  = $OrganizationName.Split("/")[-2]
            ProjectName       = '$(ProjectName)'
            RepositoryName    = '$(RepositoryName)'
          }

          New-AdoPipeline @functionInput -Verbose