resource_group_name = "jstart-cass-layered170641-eastus2"
root_cert_name = "mycert"
root_cert_passphrase = "mypassphrase"
policy_path = "root-cert-policy-rest.json"
keyvault_name = "jstartcass170641kv"