name: $(moduleName)

parameters:
- name: versioningOption
  displayName: Default publish version
  type: string
  default: patch
  values:
  - patch
  - minor
  - major
- name: uiCustomVersion
  displayName: -OR- Custom publish version
  type: string
  default: '-'
- name: removeDeployment
  displayName: Remove resources post-deployment
  type: boolean
  default: false # Not covered

variables:
- template: /Modules/ARM/.global/global.variables.yml
- name: moduleName
  value: SoftwareUpdateConfiguration
- name: pipelineCustomVersion
  value: 1.0.0

trigger:
  batch: true
  branches:
    include:
    - main
    - master
  paths:
    include:
    - Modules/ARM/.global/*
    - Modules/ARM/SoftwareUpdateConfiguration/*
    exclude:
    - Modules/ARM/SoftwareUpdateConfiguration/readme.md

stages:
- stage: Validation
  jobs:
  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.validate.yml
    parameters:
      deploymentBlocks:
      - path: $(parametersPath)/Linux_Automatic-Wave1.parameters.json
      - path: $(parametersPath)/Linux_Automatic-Wave2.parameters.json
      - path: $(parametersPath)/Linux_CatchAll.parameters.json
      - path: $(parametersPath)/Linux_ZeroDay.parameters.json
      - path: $(parametersPath)/Windows_Automatic-DefUpdate.parameters.json
      - path: $(parametersPath)/Windows_Automatic-Wave1.parameters.json
      - path: $(parametersPath)/Windows_Automatic-Wave2.parameters.json
      - path: $(parametersPath)/Windows_CatchAll.parameters.json
      - path: $(parametersPath)/Windows_ZeroDay.parameters.json

- stage: Deployment
  jobs:
  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.deploy.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      deploymentBlocks:
      - path: $(parametersPath)/Linux_Automatic-Wave1.parameters.json
      - path: $(parametersPath)/Linux_Automatic-Wave2.parameters.json
      - path: $(parametersPath)/Linux_CatchAll.parameters.json
      - path: $(parametersPath)/Linux_ZeroDay.parameters.json
      - path: $(parametersPath)/Windows_Automatic-DefUpdate.parameters.json
      - path: $(parametersPath)/Windows_Automatic-Wave1.parameters.json
      - path: $(parametersPath)/Windows_Automatic-Wave2.parameters.json
      - path: $(parametersPath)/Windows_CatchAll.parameters.json
      - path: $(parametersPath)/Windows_ZeroDay.parameters.json

- stage: Publishing
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/main','refs/heads/master'))
  jobs:
  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.publish.yml
    parameters:
      versioningOption: '${{ parameters.versioningOption }}'
      uiCustomVersion: '${{ parameters.uiCustomVersion }}'

- stage: Removal
  dependsOn: Deployment
  condition: and(succeededOrFailed(), eq( '${{ parameters.removeDeployment }}', 'true'))
  jobs:
  - template: /Modules/ARM/.global/PipelineTemplates/pipeline.jobs.remove.yml
